# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bb351162e2363677cc213544f4a2c4ed4df115a8fa64377f67bec371b7c3cf2c4eb2ade8650bab78f2a6233e48b1939987d7ed5cc9735249d24e0290dd1187a

test:
  secret_key_base: 09a7d6e9425f36154dcd3eb10c2a8533a80c4c3e9f1cf5e896201a58fcf2abb5d7592791e90b1f7fd117d854e0b8876a07ddbbb86e38e6ab78960cadefdc187a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
